version: "3.7"

services: 

    identity-db:
        environment: 
            ACCEPT_EULA: Y
            SA_PASSWORD: ${SA_PASSWORD:-Install_new!}
        ports: 
            - target: 1433
              published: ${IDENTITY_DB_PORT}

        volumes: 
            - identity-db-data:/var/opt/mssql

    seq:
        ports:
            - target: 80
              published: ${SEQ_PORT}                
        environment:
            - ACCEPT_EULA=Y

        volumes: 
            - seq-data:/data

    identity-api:
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production         
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=${IDENTITY_API_HTTPS_PORT}
            - ASPNETCORE_Kestrel__Certificates__Default__Password=Install_new!
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/budgetcast.pfx
            - Serilog__WriteTo__0__Args__serverUrl=http://seq
            - Social__Google__ClientSecret=${GOOGLE_CLIENT_SECRET}
            - Social__Google__ClientId=${GOOGLE_CLIENT_ID}
            - Social__Facebook__ClientSecret=${FACEBOOK_CLIENT_SECRET}
            - Social__Facebook__ClientId=${FACEBOOK_CLIENT_ID}
            - EmailParameters__Host=${EMAIL_SMTP_HOST:-smtp.gmail.com}
            - EmailParameters__Port=${EMAIL_SMTP_PORT:-587}
            - EmailParameters__From=${EMAIL_FROM}
            - EmailParameters__Password=${EMAIL_PASSWORD}     
            - ExternalIdentityProviders__UiRedirectUrl=https://${HOST_BASE_ADDR}:${UI_HTTPS_PORT}            
            - UiLinks__Root=https://${HOST_BASE_ADDR}:${UI_HTTPS_PORT}
            - UiLinks__ResetPassword=https://${HOST_BASE_ADDR}:${UI_HTTPS_PORT}/account/reset-password            
            - UiLinks__Login=https://${HOST_BASE_ADDR}:${UI_HTTPS_PORT}/account/login
            - IdentityManagement__ConnectionString=Server=host.docker.internal,1433;Database=IdentityDb;User Id=sa;Password=Install_new!
        ports: 
            - target: 80
              published: ${IDENTITY_API_PORT}
            - target: 443
              published: ${IDENTITY_API_HTTPS_PORT}
        volumes: 
            - ./https:/https:ro

    expenses-api:
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production            
            - ASPNETCORE_URLS=http://+:80
            - Serilog__WriteTo__0__Args__serverUrl=http://seq
            - ExpensesDb__ConnectionString=Server=host.docker.internal,1433;Database=ExpensesDb;User Id=sa;Password=Install_new!
            - UiLinks__Root=https://${HOST_BASE_ADDR}:${UI_HTTPS_PORT}
            - ServiceBusSettings__EventBusConnection=${EXPENSES_AZBUS_CONNSTR}
        ports: 
            - target: 80
              published: ${EXPENSES_API_PORT}
    
    notifications-hub:
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development            
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=${NOTIFICATIONS_API_HTTPS_PORT}
            - ASPNETCORE_Kestrel__Certificates__Default__Password=Install_new!
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/budgetcast.pfx
            - Serilog__WriteTo__0__Args__serverUrl=http://seq
            - Serilog__MinimumLevel__Override__Microsoft=Information
            - UiLinks__Root=https://${HOST_BASE_ADDR}:${UI_HTTPS_PORT}
            - Azure__SignalR__ConnectionString=${NOTIFICATIONS_SIGNALR_CONNSTR}
            - ServiceBusSettings__EventBusConnection=${NOTIFICATIONS_AZBUS_CONNSTR}
            - SignalRSettings__UseAzureSignalR=true
            - ServiceBusSettings__AzureServiceBusEnabled=false
        ports: 
            - target: 80
              published: ${NOTIFICATIONS_API_PORT}
            - target: 443
              published: ${NOTIFICATIONS_API_HTTPS_PORT}
        volumes: 
            - ./https:/https:ro

    web-spa:
        environment: 
            - ASPNETCORE_ENVIRONMENT=Prod
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=${UI_HTTPS_PORT}
            - ASPNETCORE_Kestrel__Certificates__Default__Password=Install_new!
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/budgetcast.pfx
            - Endpoints__Identity=https://${HOST_BASE_ADDR}:${IDENTITY_API_HTTPS_PORT}/api
            - Endpoints__Expenses=http://${HOST_BASE_ADDR}:${EXPENSES_API_PORT}/api
            - Endpoints__Notifications=https://${HOST_BASE_ADDR}:${NOTIFICATIONS_API_HTTPS_PORT}/hubs
        ports: 
            - target: 80
              published: ${UI_PORT}
            - target: 443
              published: ${UI_HTTPS_PORT}
    
        volumes: 
            - ./https:/https:ro

    webstatus:
        environment:
            - ASPNETCORE_ENVIRONMENT=Prod
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=${HEALTHCHECKS_UI_HTTPS_PORT}
            - ASPNETCORE_Kestrel__Certificates__Default__Password=Install_new!
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/budgetcast.pfx
            - HealthChecksUI__HealthChecks__0__Name=Identity API
            - HealthChecksUI__HealthChecks__0__Uri=https://identity-api/hc
            - HealthChecksUI__HealthChecks__1__Name=WebSPA UI
            - HealthChecksUI__HealthChecks__1__Uri=https://web-spa/hc
            - HealthChecksUI__HealthChecks__2__Name=Expenses API
            - HealthChecksUI__HealthChecks__2__Uri=http://expenses-api/hc           
            - HealthChecksUI__EvaluationTimeInSeconds=30      
        ports:
            - target: 80
              published: ${HEALTHCHECKS_UI_PORT}
            - target: 443
              published: ${HEALTHCHECKS_UI_HTTPS_PORT}

        volumes: 
            - ./https:/https:ro

volumes: 
    identity-db-data:
        external: false
    budgetcast-db-data:
        external: false
    seq-data:
        external: false    