version: "3.7"

services:

  identity-db:
    image: mcr.microsoft.com/mssql/server:2017-latest 

  budgetcast-db:
    image: mongo

  seq:
    image: datalust/seq:latest  

  dashboard-api:
    image: ${REGISTRY:-budgetcast}/dashboard.api:${PLATFORM:-linux}-${TAG:-latest}
    build: 
      context: ./Services/BudgetCast.Dashboard
      dockerfile: BudgetCast.Dashboard.Api/Dockerfile        
    depends_on: 
      - identity-db
      - budgetcast-db
      - seq

  expenses-api:
    image: ${REGISTRY:-budgetcast}/expenses.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: ./Services/BudgetCast.Expenses/src/BudgetCast.Expenses.Api/Dockerfile
      args:
        - USERNAME=appuser
    depends_on:
      - seq

  web-spa:
    image: ${REGISTRY:-budgetcast}/spa:${PLATFORM:-linux}-${TAG:-latest}
    build: 
      context: ./Web/WebSpa/BudgetCast.spa
      dockerfile: BudgetCast.Spa/Dockerfile
    depends_on: 
      - dashboard-api  
      - expenses-api
  
  webstatus:
    image: ${REGISTRY:-budgetcast}/webstatus:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: ./Web/WebStatus
      dockerfile: WebStatus/Dockerfile
    depends_on: 
      - dashboard-api
      - web-spa