version: "3.7"

services:

  identity-db:
    image: mcr.microsoft.com/mssql/server:2017-latest 
    
  seq:
    image: datalust/seq:latest  

  identity-api:
    image: ${REGISTRY:-budgetcast}/identity.api:${PLATFORM:-linux}-${TAG:-latest}
    build: 
      context: .
      dockerfile: ./Services/BudgetCast.Identity/src/BudgetCast.Identity.Api/Dockerfile        
      args:
        - USERNAME=appuser
    depends_on: 
      - identity-db
      - seq

  expenses-api:
    image: ${REGISTRY:-budgetcast}/expenses.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: ./Services/BudgetCast.Expenses/src/BudgetCast.Expenses.Api/Dockerfile
      args:
        - USERNAME=appuser
    depends_on:
      - seq

  notifications-hub:
    image: ${REGISTRY:-budgetcast}/notifications.hub:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: ./Services/BudgetCast.Notifications/src/BudgetCast.Notifications.Hub/Dockerfile
      args:
        - USERNAME=appuser
    depends_on:
      - seq

  web-spa:
    image: ${REGISTRY:-budgetcast}/spa:${PLATFORM:-linux}-${TAG:-latest}
    build: 
      context: ./Web/WebSpa/BudgetCast.spa
      dockerfile: BudgetCast.Spa/Dockerfile
    depends_on: 
      - identity-api
      - expenses-api
  
  webstatus:
    image: ${REGISTRY:-budgetcast}/webstatus:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: ./Web/WebStatus
      dockerfile: WebStatus/Dockerfile
    depends_on: 
      - identity-api
      - expenses-api
      - web-spa